# Generated by Django 2.0.5 on 2018-06-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=150)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
